### PR TITLE
Add markdown spell check & linting

### LINKED ISSUE #13: Set up remark to use roughly the same settings/linters as guides-source
That workflow is that we write special "runnable" markdowns in that repo. When we merge a pull request here, CI will build that into "regular" markdown, and integrate the result into the [guides-source](https://github.com/ember-learn/guides-source/) repo. Because we don't have linting setup in super-rentals-tutorial, often we will merge a PR over there, only to find out when it's being integrated that it failed some lints (repeated words and what not), and had to fix that in a second PR on super-rentals-tutorial.

For example:

1. PR here: https://github.com/ember-learn/super-rentals-tutorial/pull/73
2. Pushed to guides-source: https://github.com/ember-learn/guides-source/pull/1126
3. Failed guides-source CI due to "qunit-dom" not being a word in the dictionary
4. Fixed in 7502df14b5267648f8442f590b709c1d9f10e181
5. (guides-source PR updated and CI failure resolved)

It would be nice to "roughly mirror" (i.e. duplicate) the linting setup we used in guides-source into this repo, so the step 1 would have failed CI and we would have fixed it before merging  the PR and avoid step 3, 4, 5.

### PR DESCRIPTION
**Pull request by maxwondercorn**
Add the same markdown linting setup as used in `guides-source` and `cli-guides`.  Run the `lint:md` script to manually lint.  Add script to CI when you want to automate it. Fixes #13 

* Added common spell checking/linting setup
* Updated CONTRIBUTING.md with linting information/requirements
* Linted and corrected existing content.  Reference errors still exist
* Added repo only words to the `.local.dic` dictionary so spell check passes.  Also spell checked and included words from un-merged `Part-2` branch

Notes:
* See linting & spelling errors sections in CONTRIBUTING.md
* README and CONTRIBUTING are ignored (`.remarkignore`) by the linter. I did lint them and made corrections
* I will open a PR on `guides-source` to add the tutorial `.local.dic` words to the guides dictionary. PR ember-learn/guides-source#1127 needs to be merged first

### CODE REVIEW

**Comment by chancancode** [comment]
The upstream PRs has been merged!

**Comment by chancancode** [comment]
@maxwondercorn Thanks again for working on this! Since the upstream PRs are merged, is there anything else we need to do here?

**Comment by maxwondercorn** [comment]
@chancancode If this repo will be standalone this PR should be merged so contributors can verify the linting before it's merged into `guides-source`.  

New content linting errors can be fixed before merging. If a new word is flagged as a spelling error it needs to be added to tutorial's `.local-dic`.  Then a `guides-source` PR created to add the word(s) to that `.local-dic`.

I know this a bit convoluted and I hope my explanation makes sense. This would probably be easier if we were using a mono repo that could share a single `.local-dic`.

Of course there may another way around this with some git "magic" that I don't know about 🤔 What I don't know about git far exceeds what I do know 😀

**Comment by chancancode** [comment]
Yep that makes sense to me! I just wanted to clarify that when you say "PR ember-learn/guides-source#1127 needs to be merged first", you didn't mean we need to "rebase" this PR after merging the upstream stuff. I'll work on getting this merged then! Thank you again for helping out on this, this is going to be super useful.

**Comment by maxwondercorn** [comment]
We just wanted to make sure the guides-source PR was merged because it already included all the "misspelled" words from the tutorial in it's `.local.dic` file. 

If there isn't any new "misspelled" words you shouldn't have to do anything to pass linting on the next merge.

**Comment by chancancode** [comment]
@maxwondercorn I squashed/rebased your branch and set it up to run as part of the build! Hopefully it will pass on CI and we should be good to merge! (Not sure why the squashed commit didn't show your GH profile correctly?!)

**Comment by maxwondercorn** [comment]
👍 It looks like the GH profile is wonky because I updated my avatar/picture after the PR was created.

**Pull request merged**
