### PR TITLE
Add links for learning more (part 4 of 4)

### PR DESCRIPTION
**Pull request by aredshaw**
I have made the changes according to the links and fixes you list for [Issue #163](https://github.com/ember-learn/super-rentals-tutorial/issues/163). I had already added links last night by searching your site as well as some outside MDN links, but some of the links I found were different, so I'm sure yours are the right ones. These are all according to your list.

### CODE REVIEW

**Review by ijlee2 — CHANGES_REQUESTED** [review]
Hi, @aredshaw. Thanks again for making your first contribution to the Super Rentals tutorial.

In your changes for `10-service-injection.md`, I noticed that not all links have been added correctly. I did not review the other two files just yet.

Will you go through all 3 files and check that:

- You removed `*` (italics) after you have added a link
- For links whose domain is `guides.emberjs.com`, use a relative path that begins with `../../..` and ends with `/` (the trailing slash must be included, except when the link includes a `#` for an anchor)
- Replace only the placeholder links that are listed in the [issue description](https://github.com/ember-learn/super-rentals-tutorial/issues/163#issue-718488361)

To see examples of patterns in code change that I'm looking for, you can have a look at https://github.com/ember-learn/super-rentals-tutorial/pull/165/files .

If you have questions, please feel free to comment in this pull request or in the issue.

Cheers,

**Comment by aredshaw** [comment]
No problem. I will make these changes at the end of the day.

**Comment by ijlee2** [comment]
@aredshaw Sounds good, thanks!

**Comment by chancancode** [comment]
FAIW @ijlee2 the * (italics) were intended to be kept around even when it's linked, to signify it's a "well known"/"well defined" technical term, I think it's used somewhat consistently in the tutorial.

**Comment by chancancode** [comment]
If you think they are now redundant with the links, I can see the argument for that as well, but:

1. There will now be inconsistencies between the linked terms, not a big deal, we can fix the existing links

2. The linked and unlinked terms will now look more different, which is a (somewhat negative) unintended consequence

**Comment by ijlee2** [comment]
@chancancode Ah, I thought the `*` was a part of the placeholder link syntax and needed to be removed after we add the link.

If we do want to add `*` back, I can fix the links in chapters 1-3. As for the remaining chapters, we'll want to quickly notify the contributors. What do you think?

**Comment by chancancode** [comment]
Sounds good. Either way it's easy enough to fix before or after merging the PRs.

**Comment by ijlee2** [comment]
@aredshaw Will you leave the `*` as is? Thanks.

**Comment by aredshaw** [comment]
Fine, I will leave the * so the links are italicized. That's what I thought they were there for at first. I'll fix the other issues.

**Comment by aredshaw** [comment]
I made a separate pull request for this because it was easier than backtracking on which wrong links I put in. You can see it here: https://github.com/ember-learn/super-rentals-tutorial/pull/167.

**Comment by aredshaw** [comment]
I made a separate pull request for this because it was easier than backtracking on which wrong links I put in. You can see it here: https://github.com/ember-learn/super-rentals-tutorial/pull/167.

**Comment by ijlee2** [comment]
@aredshaw Sounds good, I'll close this pull request.

**Pull request closed without merging**
