### PR TITLE
Update patch to match updated blueprint for app/templates/application.hbs

### PR DESCRIPTION
**Pull request by kategengler**
Should fix beta build

### CODE REVIEW

**Comment by kategengler** [comment]
This will probably fail against release. @chancancode what was the strategy for when beta and release diverge?

**Comment by chancancode** [comment]
I think I meant to plumb through some of the cfg stuff so that you make the blocks conditional, something like:

     ```run:file:patch ... cfg=beta
     ```

But iirc I have never gotten to it. I think an okay workaround for this specific case is to normalize it with a hidden command:

     ```run:command hidden=true
     #[cfg(unix)]
     sed 's/--//g' app/templates/application.hbs
     ```
     
     ```run:file:patch lang=handlebars cwd=super-rentals filename=app/templates/application.hbs
      @@ -1,7 +1 @@
      -{{page-title "SuperRentals"}}
      -
      -{{! The following component displays Ember's default welcome message. }}
      -<WelcomePage />
      -{{! Feel free to remove this! }}
      -
     ```

It's not a perfect solution because the reader may notice the difference in the release version, but in this case the difference is probably minor enough that it doesn't trip anyone up.

**Comment by chancancode** [comment]
@kategengler build is green!

**Comment by kategengler** [comment]
🎉 Thanks for updating this PR, @chancancode I was just going to be lazy and let it sit until 5.1 released next week 🙈

**Pull request merged**
